
### Create a new User
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name":"Bianca6 Smith",
    "email":"bianca6@gmail.com",
    "password": "1234567"
}

### Return post
GET http://localhost:3003/post/getpost
Content-Type: application/json

{
    "id":"1675379034720"
}

### Create a new Post
POST http://localhost:3003/post/create
Content-Type: application/json
Authorization: 1675001631299

{
    "photo" : "Foto",
    "description": "foto da viagem",
    "type": "normal",
    "createdAt": "02/01/2023"
}

### Create a new Friendship
POST http://localhost:3003/friendship/create
Content-Type: application/json
Authorization: 1675001631299

{
    "friendId":"1675019596015"
}

### Delete Friendship
DELETE http://localhost:3003/friendship
Content-Type: application/json
Authorization: 1675001631299

{
    "friendId":"1675019596015"
}

### Return Feeds freands
GET http://localhost:3003/post/getfeedsfreands
Content-Type: application/json
Authorization: 1675001631299

### return feed by type 
GET http://localhost:3003/post/getfeeds
Content-Type: application/json

{
    "type":"normal"
}

### Like Post
POST http://localhost:3003/like/create
Content-Type: application/json
Authorization: 1675001631299

{
    "postId":"1675379034720"
}

### Delete Like Post
DELETE  http://localhost:3003/like
Content-Type: application/json
Authorization: 1675001631299

{
    "postId":"1675379034720"
}

### Comment Post
POST   http://localhost:3003/comments
Content-Type: application/json
Authorization: 1675001631299

{
    "comment":"Linda foto",
    "postId":"1675379034720"
}