
### Create a new User
POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Bianca Smith",
    "email":"bianca@gmail.com",
    "password": "1234567"
}

### Return all post
GET http://localhost:3003/posts/1675001631299
Content-Type: application/json

### Create a new Post
POST http://localhost:3003/post
Content-Type: application/json

{
    "photo" : "Foto",
    "description": "foto da viagem",
    "type": "normal",
    "created_at": "" ,
    "authorId": "1675001631299"
}

### Create a new Friendship

POST http://localhost:3003/friendship
Content-Type: application/json

{
    "friend":"1675081679184",
    "authorId": "1675001631299"
}

### Delete Friendship

DELETE http://localhost:3003/friendship/1675001631299
Content-Type: application/json

{
    "friend":"1675081679184"
}

### Return all Friend
GET http://localhost:3003/friendship/1675001631299
Content-Type: application/json

